import typing as tp


class FileSystemMounter(tp.Protocol):
    def is_mounted(self) -> bool: ...
    def mount(self, *, fail: bool = True) -> None: ...
    def unmount(self, *, fail: bool = True) -> None: ...
